name: yolov3-tf2-cpu

dependencies:
  - python==3.8
  - pip
  - pylint
  - jupyterlab
  - pip:
    - tensorflow==2.12.0
    - opencv-python==4.2.0.32
    - matplotlib
    - lxml
    - tqdm
    - -e .
